name: Republish
description: 'Republish SARIF for languages that were not scanned in this PR'
inputs:
  projects:
    description: 'Projects scanned in this PR'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Check for PR
      id: pr
      if: github.event_name == 'pull_request'
      run: |
        echo "::set-output In PR"
      shell: bash

    - name: Debug output
      if: steps.pr
      env: 
        projects: ${{ inputs.projects }}
      run: |
        echo "$projects"
      shell: bash

    - uses: actions/github-script@v7
      if: steps.pr
      env:
        projects: ${{ inputs.projects }}
      with:
        script: |
          const path = require('node:path')
          const action_path = process.env.GITHUB_ACTION_PATH
          const script = require(path.join(action_path, 'scripts/republish-sarif.js'))
          script(github, context, core)

    - uses: github/codeql-action/upload-sarif@v3
      if: steps.pr && hashFiles('sarif/*.sarif') != ''
      with:
        sarif_file: sarif
