name: Republish
description: 'Republish SARIF for languages that were not scanned in this PR'
inputs:
  projects:
    description: 'Projects scanned in this PR'
    required: true
    type: string
  merged-only:
    description: 'Only republish SARIF when the PR merges'
    required: false
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    # Download SARIF files from previous analyses (for missing categories)
    - uses: actions/github-script@v7
      if: github.event_name == 'pull_request' && ( inputs.merged-only == false || github.event.pull_request.merged == true )
      env:
        projects: ${{ inputs.projects }}
        SARIF_MODE: 'download'
      with:
        script: |
          const path = require('node:path')
          const action_path = process.env.GITHUB_ACTION_PATH
          const script = require(path.join(action_path, 'republish-sarif.js'))
          script(github, context, core)

    # Scenario 1: PR mode - upload SARIF files via GitHub API to the PR itself
    - name: Upload SARIF files to PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request' && github.event.pull_request.merged != true && hashFiles('sarif/*.sarif') != ''
      env:
        SARIF_MODE: 'upload'
        SARIF_DIR: './sarif'
      with:
        script: |
          const path = require('node:path')
          const action_path = process.env.GITHUB_ACTION_PATH
          const script = require(path.join(action_path, 'republish-sarif.js'))
          
          // Override context for PR upload
          const prContext = {
            ...context,
            sha: context.payload.pull_request.head.sha,
            ref: `refs/pull/${context.payload.pull_request.number}/merge`
          }
          
          script(github, prContext, core)

    # Scenario 2: Merged mode - upload SARIF files via GitHub API to the PR target
    - name: Upload SARIF files to PR target
      uses: actions/github-script@v7
      if: github.event.pull_request.merged == true && hashFiles('sarif/*.sarif') != ''
      env:
        SARIF_MODE: 'upload'
        SARIF_DIR: './sarif'
      with:
        script: |
          const path = require('node:path')
          const action_path = process.env.GITHUB_ACTION_PATH
          const script = require(path.join(action_path, 'republish-sarif.js'))
          
          // Override context for target branch upload
          const targetContext = {
            ...context,
            sha: context.payload.pull_request.head.sha,
            ref: `refs/heads/${context.payload.pull_request.base.ref}`
          }
          
          script(github, targetContext, core)
