name: Republish
description: 'Republish SARIF for languages that were not scanned in this PR'
inputs:
  languages:
    description: 'Languages scanned in this PR'
    required: true
    type: object

  republish-sarif:
    name: Republish SARIF scans for languages not scanned in this PR
    runs-on: ubuntu-latest
    needs: changes
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout script
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/scripts/republish-sarif.js
      - uses: actions/github-script@v7
        env:
          languages: ${{ inputs.languages }}
        with:
          script: |
            const script = require('.github/scripts/republish-sarif.js')
            script(github, context, core)
      - uses: github/codeql-action/upload-sarif@v3
        if: ${{ hashFiles('sarif/*.sarif') != '' }}
        with:
          sarif_file: sarif
