name: Republish
description: 'Republish SARIF for languages that were not scanned in this PR'
inputs:
  projects:
    description: 'Projects scanned in this PR'
    required: true
    type: object

runs:
  using: 'composite'
  steps:
    - name: Check for PR
      id: pr
      run: |
        echo "::set-output In PR"
      shell: bash

    - name: Checkout script
      if: steps.pr
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github/scripts/republish-sarif.js
        sparse-checkout-cone-mode: false
    - uses: actions/github-script@v7
      if: steps.pr
      env:
        languages: ${{ inputs.projects.languages }}
      with:
        script: |
          const script = require('.github/scripts/republish-sarif.js')
          script(github, context, core)
    - uses: github/codeql-action/upload-sarif@v3
      if: steps.pr && hashFiles('sarif/*.sarif') != ''
      with:
        sarif_file: sarif
