name: Scan
description: 'Analyze a project in a monorepo'

runs:
  using: 'composite'
  steps:
    - name: Checkout project folders to scan
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{ matrix.project.sparse_checkout }}
          .github/actions/code-scanning-custom-analysis/**/*
          .github/workflows/**/*
        sparse-checkout-cone-mode: false

    # Initializes CodeQL for scanning, if required
    - name: Initialize CodeQL (build mode none/auto)
      if: matrix.project.build_mode == 'none' || matrix.project.build_mode == 'auto'
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.project.language }}
        build-mode: ${{ matrix.project.build_mode }}
        config: ${{  matrix.project.codeql_config }}

    # Show manual Action, if using manual/other build mode
    - name: Initialize CodeQL and build (manual)
      if: matrix.project.build_mode == 'manual' || matrix.project.build_mode == 'other'
      run: |
        echo "Build mode: ${{ matrix.project.build_mode }}"
        ls -la ./.github/actions/code-scanning-custom-analysis/*
      shell: bash

    # Build the project, manually, if required
    # Scanning with CodeQL and uploading the SARIF will be handled by the last step, below
    - name: Initialize CodeQL and build (manual)
      if: matrix.project.build_mode == 'manual'
      uses: ./.github/actions/code-scanning-custom-analysis/
      with:
        language: ${{  matrix.project.language }}
        codeql-config: ${{  matrix.project.codeql_config }}
        name: ${{  matrix.project.name }}

    # Scan the project, if we have a non-CodeQL build
    # This will require a SARIF upload step in the custom analysis workflow
    - name: Scan project (non CodeQL)
      if: matrix.project.build_mode == 'other'
      uses: ./.github/actions/code-scanning-custom-analysis/
      with:
        language: ${{  matrix.project.language }}
        name: ${{  matrix.project.name }}

    # Perform the CodeQL analysis, if we have a CodeQL build
    # This will upload the SARIF for you
    - name: Perform CodeQL Analysis
      id: codeql-analyze
      if: matrix.project.build_mode != 'other'
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.project.language }};project:${{ matrix.project.name }}"
        upload: false
        output: sarif-results

    # Echo the outputs of the CodeQL analysis
    - name: Echo CodeQL Analysis Outputs
      if: matrix.project.build_mode != 'other' && env.ACTIONS_RUNNER_DEBUG == 'true'
      run: |
        echo "DB Locations: ${{ steps.codeql-analyze.outputs.db-locations }}"
        echo "SARIF Output: ${{ steps.codeql-analyze.outputs.sarif-output }}"
        echo "SARIF ID: ${{ steps.codeql-analyze.outputs.sarif-id }}"
      shell: bash

    # Parse the db-locations output and set the sarif_file path
    # - db-locations: {javascript:/home/runner/work/_temp/codeql_databases/javascript}
    # - sarif-output: /home/runner/work/sample-javascript-monorepo/sample-javascript-monorepo/sarif-results
    - name: Set SARIF file path
      id: set-sarif-file-path
      if: matrix.project.build_mode != 'other'
      uses: actions/github-script@v7
      with:
        script: |
          const dbLocations = JSON.parse('${{ steps.codeql-analyze.outputs.db-locations }}');
          const language = Object.keys(dbLocations)[0];
          const sarifFilePath = `${{ steps.codeql-analyze.outputs.sarif-output }}/${language}.sarif`;
          console.log(`SARIF file path: ${sarifFilePath}`);
          return { sarif_file: sarifFilePath };

    # Validate location of sarif results
    - name: echo dir
      if: matrix.project.build_mode != 'other' && env.ACTIONS_RUNNER_DEBUG == 'true'
      run: |
        ls -ls
        ls -ls ${{ steps.codeql-analyze.outputs.db-locations }}
      shell: bash

    - name: Annotate CodeQL Alert SARIF with Project tag
      if: matrix.project.build_mode != 'other'  
      uses: advanced-security/monorepo-code-scanning-action/sarif-project-annotator@annotate-sarif
      with:
        project: ${{ matrix.project.name }}
        sarif_file: ${{ steps.set-sarif-file-path.outputs.sarif_file }}
        output_file: ${{ steps.set-sarif-file-path.outputs.sarif_file }}        

    - name: Upload SARIF with project tags
      if: matrix.project.build_mode != 'other'
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: "/language:${{ matrix.project.language }};project:${{ matrix.project.name }}"
        sarif_file: ${{ steps.set-sarif-file-path.outputs.sarif_file }}
