name: Scan
description: 'Analyze a project in a monorepo'

runs:
  using: 'composite'
  steps:
    - name: Checkout project folders to scan
      uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ matrix.project.sparse_checkout }}

    # Initializes the CodeQL tools for scanning
    - name: Initialize CodeQL (build mode none/auto)
      if: matrix.project.build_mode == 'none' || matrix.project.build_mode == 'auto'
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.project.language }}
        build-mode: ${{ matrix.project.build_mode }}
        config: ${{  matrix.project.codeql_config }}

    - name: Initialize CodeQL (manual build)
      if: matrix.project.build_mode == 'manual'
      uses: ./.github/workflows/codeql-custom-analysis.yml
      with:
        language: ${{  matrix.project.language }}
        codeql-config: ${{  matrix.project.codeql_config }}
        name: ${{  matrix.project.name }}

    - name: Perform CodeQL Analysis
      if: matrix.project.build_mode != 'other'
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.project.language }};project:${{ matrix.project.name }}"
