name: Annotate
description: 'Annotate SARIF to include information about the projects on each alert'
inputs:
  project:
    description: 'The name of the project to annotate as a tag'
    required: true
  # projects-json:
  #   description: 'TESTING ONLY: Path to the JSON file that defines the projects to build'
  #   required: false
  sarif_file:
    required: true
    description: 'The CodeQL SARIF result file'
  output_file:
    required: true
    description: 'The output SARIF file path'
runs:
  # using: node20
  # main: sarif-project-annotator.js
  using: 'composite'
  steps:
    - name: Run SARIF project annotator via github-script
      id: annotate-sarif
      #if: ${{ inputs.projects-json == '' && inputs.build-xml != '' }}
      uses: actions/github-script@v7
      # env:
      #   filename: ${{ inputs.build-xml }}
      #   variables: ${{ inputs.variables }}
      with:
        result-encoding: string
        script: |
          const path = require('node:path')
          const action_path = process.env.GITHUB_ACTION_PATH
          const script = require(path.join(action_path, 'sarif-project-annotator.js'))
          return script(github, context, core)  