name: Republish
description: 'Replay CodeQL check status for languages not scanned in this PR'
inputs:
  languages:
    description: 'Languages scanned in this PR'
    required: true
    type: object

  replay-checks:
    name: Replay CodeQL check status for languages not scanned in this PR
    runs-on: ubuntu-latest
    needs: changes
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout script
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/scripts/replay-checks.js
      - uses: actions/github-script@v7
        env:
          languages: ${{ inputs.languages }}
        with:
          script: |
            const script = require('.github/scripts/replay-checks.js')
            script(github, context, core)
